stages:
  load_data:
    cmd: python src/get_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - Original_data/flight_data.xlsx
    outs:
    - data/raw/flight_data.csv
  
  filter_data:
    cmd: python src/feature_engineering.py --config=params.yaml
    deps:
    - src/feature_engineering.py
    - data/raw/flight_data.csv
    outs:
    - data/filtered/final_data.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - data/filtered/final_data.csv
    - src/split_data.py
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  model_train_evaluate:
    cmd: python src/model_train_evaluate.py --config=params.yaml
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - src/model_train_evaluate.py
    params:
    - estimators.CatBoost.params.iterations
    - estimators.CatBoost.params.learning_rate
    - estimators.CatBoost.params.depth
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib
