base:
  project: flightfare-project
  random_state: 42
  target: Price

data_source:
  gdrive_source: Original_data/flight_data.xlsx

load_data:
  raw_data_csv: data/raw/flight_data.csv

filter_data:
  filter_data_csv: data/filtered/final_data.csv

split_data:
  train_data: data/processed/train.csv
  test_data: data/processed/test.csv
  test_size: 0.2

estimators:
  CatBoost:
    params:
      iterations: 1000
      learning_rate: 0.5718
      depth: 8

model_dir: saved_models
